# Generated by Django 5.2.4 on 2025-09-09 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "created_at"], name="activities_user_id_3c9068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "category"], name="activities_user_id_935e47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "frequency"], name="activities_user_id_d61b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streakentry",
            index=models.Index(
                fields=["activity", "date"], name="streak_entr_activit_9a15ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streakentry",
            index=models.Index(
                fields=["activity", "date", "completed"],
                name="streak_entr_activit_333b46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="streakentry",
            index=models.Index(
                fields=["date", "completed"], name="streak_entr_date_476e5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streakentry",
            index=models.Index(
                fields=["activity", "completed"], name="streak_entr_activit_2bb1d9_idx"
            ),
        ),
    ]
